name: c1
on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
  workflow_dispatch:
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger1
        uses: actions/checkout@v2
      - name: Trigger2
        uses: ./docker
        with:
          args: |
            NOVO=ola
            ARG2=bar
