name: Matrix

on:
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14, 16, 20]
        typ: ['db1', 'db2'] 
    steps:
      - run: |
        echo "${{ matrix.version }}"
        echo "${{ matrix.typ }}"