name: 'Hello World'
description: 'Greet someone'
inputs:
  versao:
    description: 'Define env name'     
    required: true
    default: 'prod'
  tipo:
    description: 'Define env name'     
    required: true
    default: 'tipo'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:

    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - name: passo1
      run: |
        echo "${{ inputs.versao }}"
        echo "${{ inputs.tipo }}"